name: Deploy to EC2

on:
  push:
    branches:
      - main
      - feature/BAC-24

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.8'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.DOCKER_IMAGE }} .

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ vars.AWS_EC2_USER }}@${{ secrets.AWS_EC2_IP }} << 'EOF'
            docker stop ${{ vars.DOCKER_NAME }} || true
            docker rm ${{ vars.DOCKER_NAME }} || true
            docker run -d --name ${{ vars.DOCKER_NAME }} -p 8080:8080 ${{ vars.DOCKER_IMAGE }}
          EOF